services:
  frontend-tests:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    environment:
      - FORCE_COLOR=1
      - npm_config_color=true
      - TERM=xterm-256color
    tty: true
    command: sh -c "npm install && npm run test:coverage"