name: CI - tptutor backend

on:
  push:
    branches: [ master, main ]
    paths:
      - "backend/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  backend-ci:
    name: Backend CI (Node)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      # Instalación flexible (funciona con o sin package-lock.json)
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Usando npm ci..."
            npm ci
          else
            echo "No hay package-lock.json, usando npm install..."
            npm install
          fi

      - name: Lint (si existe)
        run: npm run lint --if-present

      - name: Test (si existe)
        run: npm test --if-present

      - name: Build (si existe)
        run: npm run build --if-present

      - name: Mostrar scripts disponibles
        run: npm run
